// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.vcs.service;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.server.*;
import javax.xml.rpc.handler.HandlerInfo;
import com.sun.xml.rpc.client.HandlerChainImpl;

public class Msg_Tie
    extends com.sun.xml.rpc.server.TieBase implements SerializerConstants {
    
    
    
    public Msg_Tie() throws Exception {
        super(new com.vcs.service.binding.HelloMsgService_SerializerRegistry().getRegistry());
        initialize(internalTypeMappingRegistry);
    }
    
    /*
     * This method does the actual method invocation for operation: getMsg
     */
    private void invoke_getMsg(StreamingHandlerState state) throws Exception {
        
        com.vcs.service.Msg_getMsg_RequestStruct myMsg_getMsg_RequestStruct = null;
        Object myMsg_getMsg_RequestStructObj =
            state.getRequest().getBody().getValue();
        
        if (myMsg_getMsg_RequestStructObj instanceof SOAPDeserializationState) {
            myMsg_getMsg_RequestStruct = (com.vcs.service.Msg_getMsg_RequestStruct)((SOAPDeserializationState)myMsg_getMsg_RequestStructObj).getInstance();
        } else {
            myMsg_getMsg_RequestStruct = (com.vcs.service.Msg_getMsg_RequestStruct)myMsg_getMsg_RequestStructObj;
        }
        
        try {
            java.lang.String result = 
                ((com.vcs.service.Msg) getTarget()).getMsg(myMsg_getMsg_RequestStruct.getString_1());
            com.vcs.service.Msg_getMsg_ResponseStruct myMsg_getMsg_ResponseStruct =
                new com.vcs.service.Msg_getMsg_ResponseStruct();
            SOAPHeaderBlockInfo headerInfo;
            myMsg_getMsg_ResponseStruct.setResult(result);
            
            SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_getMsg_getMsgResponse_QNAME);
            bodyBlock.setValue(myMsg_getMsg_ResponseStruct);
            bodyBlock.setSerializer(ns2_myMsg_getMsg_ResponseStruct_SOAPSerializer);
            state.getResponse().setBody(bodyBlock);
        } catch (javax.xml.rpc.soap.SOAPFaultException e) {
            SOAPFaultInfo fault = new SOAPFaultInfo(e.getFaultCode(),
                e.getFaultString(), e.getFaultActor(), e.getDetail());
            SOAPBlockInfo faultBlock = new SOAPBlockInfo(com.sun.xml.rpc.encoding.soap.SOAPConstants.QNAME_SOAP_FAULT);
            faultBlock.setValue(fault);
            faultBlock.setSerializer(new SOAPFaultInfoSerializer(false, e.getDetail()==null));
            state.getResponse().setBody(faultBlock);
            state.getResponse().setFailure(true);
        }
    }
    
    /*
     * This method must determine the opcode of the operation that has been invoked.
     */
    protected void peekFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        if (bodyReader.getName().equals(ns1_getMsg_getMsg_QNAME)) {
            state.getRequest().setOperationCode(getMsg_OPCODE);
        }
        else {
            throw new SOAPProtocolViolationException("soap.operation.unrecognized", bodyReader.getName().toString());
        }
    }
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case getMsg_OPCODE:
                deserialize_getMsg(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the getMsg operation.
     */
    private void deserialize_getMsg(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        java.lang.Object myMsg_getMsg_RequestStructObj =
            ns2_myMsg_getMsg_RequestStruct_SOAPSerializer.deserialize(ns1_getMsg_getMsg_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_getMsg_getMsg_QNAME);
        bodyBlock.setValue(myMsg_getMsg_RequestStructObj);
        state.getRequest().setBody(bodyBlock);
    }
    
    
    /*
     * This method must invoke the correct method on the servant based on the opcode.
     */
    protected void processingHook(StreamingHandlerState state) throws Exception {
        switch (state.getRequest().getOperationCode()) {
            case getMsg_OPCODE:
                invoke_getMsg(state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", java.lang.Integer.toString(state.getRequest().getOperationCode()));
        }
    }
    
    public java.lang.String getDefaultEnvelopeEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public java.lang.String getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    
    /*
     * This method must determine the opcode of the operation given the QName of the first body element.
     */
    public int getOpcodeForFirstBodyElementName(QName name) {
        if (name == null) {
            return InternalSOAPMessage.NO_OPERATION;
        }
        if (name.equals(ns1_getMsg_getMsg_QNAME)) {
            return getMsg_OPCODE;
        }
        return super.getOpcodeForFirstBodyElementName(name);
    }
    
    
    private Method internalGetMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
        
        Method theMethod = null;
        
        switch(opcode) {
            case getMsg_OPCODE:
                {
                    Class[] carray = { java.lang.String.class };
                    theMethod = (com.vcs.service.Msg.class).getMethod("getMsg", carray);
                }
                break;
            
            default:
        }
        return theMethod;
    }
    
    private Method[] methodMap = new Method[1];
    
    /*
     * This method returns the Method Obj for a specified opcode.
     */
    public Method getMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
         
        if (opcode <= InternalSOAPMessage.NO_OPERATION ) {
            return null;
        }
         
        if (opcode >= 1 ) {
            return null;
        }
         
        if (methodMap[opcode] == null)  {
            methodMap[opcode] = internalGetMethodForOpcode(opcode);
        }
         
        return methodMap[opcode];
    }
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    
    protected boolean preHandlingHook(StreamingHandlerState state) throws Exception {
        boolean bool = false;
        bool = super.preHandlingHook(state);
        return bool;
    }
    
    
    protected void postResponseWritingHook(StreamingHandlerState state) throws Exception {
        super.postResponseWritingHook(state);
    }
    
    private void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns2_myMsg_getMsg_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.vcs.service.Msg_getMsg_ResponseStruct.class, ns2_getMsgResponse_TYPE_QNAME);
        ns2_myMsg_getMsg_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.vcs.service.Msg_getMsg_RequestStruct.class, ns2_getMsg_TYPE_QNAME);
    }
    
    private static final javax.xml.namespace.QName portName = new QName("http://vcs.com/msg/wsdl", "Msg");
    private static final int getMsg_OPCODE = 0;
    private static final javax.xml.namespace.QName ns1_getMsg_getMsg_QNAME = new QName("http://vcs.com/msg/wsdl", "getMsg");
    private static final javax.xml.namespace.QName ns2_getMsg_TYPE_QNAME = new QName("http://vcs.com/msg/types", "getMsg");
    private CombinedSerializer ns2_myMsg_getMsg_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_getMsg_getMsgResponse_QNAME = new QName("http://vcs.com/msg/wsdl", "getMsgResponse");
    private static final javax.xml.namespace.QName ns2_getMsgResponse_TYPE_QNAME = new QName("http://vcs.com/msg/types", "getMsgResponse");
    private CombinedSerializer ns2_myMsg_getMsg_ResponseStruct_SOAPSerializer;
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "http://vcs.com/msg/types"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
